name: Hello Workflow

on: 
  push:
    branches:
      - main

jobs:
  say_hello:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run Hello script
        run: echo "Hello, GitHub Actions!"